sudo: false
language: php
php:
  - 5.6
  - 7
  - 7.1

install:
  - composer install --prefer-dist

script:
  - composer cs
  - composer test

matrix:
  allow_failures:
  - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files
